### ISSUE TITLE
Please make this open-source.

### ISSUE THREAD

**Issue by tnb24** [Vivek-Kolhe/Nyaa-API#3]
title. That way we can host it ourselves and not rely on heroku

**Comment by Vivek-Kolhe** [comment]
> title. That way we can host it ourselves and not rely on heroku

Na, Sorry. I still have no plans for making it open-source yet. There are still many other sources you can use instead of this API. You can use nyaa python package to satisfy your needs or I saw there are bunch of nyaa scraping scripts available on github.

**Comment by tnb24** [comment]
why tho and i specifically need this api cuz im currently relying on an api which has a link (if you know what i mean)

**Comment by Vivek-Kolhe** [comment]
Lol, if you're relying on API, then why not use it?
Anyways I've my exams rn, I'll think about it later.
